### ISSUE TITLE
Support newer FX formats

### ISSUE THREAD

**Issue by stevewgr** [stevewgr/ko#87]
#### Description

Even though we keep the client old school, there are some nice effects and in HDR quality in newer clients that would be nice adapting into the old version.

#### Tasks

- [ ] Support newer FX Bundle formats (28 instead of 16)
- [ ] Support newer FX Parts formats (at least just loading them for now)
- [ ] Replace old fx directory from latest version in the 1097 client
- [ ] Note that also this task needs to be done for this to work: https://github.com/stevewgr/ko/issues/86
