### ISSUE TITLE
Implement DirectX device caching mechanism

### ISSUE THREAD

**Issue by stevewgr** [stevewgr/ko#91]
#### Description
 
Note that newer clients implement CN3Device to wrap around every DirectX call.

This is really helpful when wanting to cache certain resources or specific DirectX calls.

This is also helpful when writing statistics and calculating draw calls with the need for 3rd party tools.

#### Tasks

- [ ] Implement a wrapper around all DirectX-9 calls called CN3Device
- [ ] Cache some of the draw calls, especially setting render states could be cached
- [ ] Replace the 3D device pointer with CN3Device wrapper
